name: 'Terraform S3 Pipeline'

on:
  push:
    branches: [ "main" ]                # Se ejecuta solo cuando haces push a la rama main
    paths:
      - 'environments/**'               # Solo si se modifican archivos dentro de la carpeta environments/

permissions:
  contents: read                        # Permisos mínimos para clonar el repositorio

jobs:
  detect-environments:
    name: 'Detect Changed Environments'
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.detect.outputs.environments }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Detect changed environments
        id: detect
        run: |
          # Obtiene archivos cambiados entre el último commit y el anterior
          changed_files=$(git diff --name-only HEAD~1 HEAD)

          # Filtra solo los que están dentro de 'environments/', extrae el nombre del entorno
          changed_envs=$(echo "$changed_files" | grep '^environments/' | cut -d'/' -f2 | sort -u)

          # Si no hay entornos, setear []
          if [ -z "$changed_envs" ]; then
            echo "environments=[]" >> $GITHUB_OUTPUT
            echo "No environments changed"
          else
            # Arma un JSON válido
            envs_json=$(echo "$changed_envs" | jq -R -s -c 'split("\n")[:-1] | map(select(length > 0))')
            echo "environments=$envs_json" >> $GITHUB_OUTPUT
            echo "Changed environments: $envs_json"
          fi

  terraform:
    name: 'Terraform (${{ matrix.environment }})'
    runs-on: ubuntu-latest
    needs: detect-environments
    if: needs.detect-environments.outputs.environments != '[]'
    strategy:
      matrix:
        environment: ${{ fromJson(needs.detect-environments.outputs.environments) }}

    defaults:
      run:
        shell: bash
        working-directory: ./environments/${{ matrix.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false \
             -var="bucket_name=${{ vars.BUCKET_NAME }}" \
             -var="environment=${{ matrix.environment }}"
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

  terraform-apply:
    name: 'Terraform Apply (${{ matrix.environment }})'
    runs-on: ubuntu-latest
    needs: terraform
    if: needs.detect-environments.outputs.environments != '[]' && github.ref == 'refs/heads/main' && github.event_name == 'push'
    strategy:
      matrix:
        environment: ${{ fromJson(needs.detect-environments.outputs.environments) }}

    defaults:
      run:
        shell: bash
        working-directory: ./environments/${{ matrix.environment }}

    steps:
      - name: Wait for manual approval
        uses: trstringer/manual-approval@v1
        with:
          approvers: cristopher
          minimum-approvals: 1
          instructions: "Revisá el Terraform Plan y aprobá para continuar con el Apply."

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false \
             -var="bucket_name=${{ vars.BUCKET_NAME }}" \
             -var="environment=${{ matrix.environment }}"
