name: 'Terraform S3 Pipeline'

on:
  push:
    branches: [ "main" ]                # Se ejecuta solo cuando haces push a la rama main
    paths:
      - 'environments/**'               # Solo si se modifican archivos dentro de la carpeta environments/

permissions:
  contents: read                        # Permisos mínimos para clonar el repositorio

jobs:
  detect-environments:
    name: 'Detect Changed Environments'
    runs-on: ubuntu-latest              # Usa un runner Ubuntu actualizado
    outputs:
      environments: ${{ steps.detect.outputs.environments }}  # Exporta los entornos detectados para otros jobs
    steps:
      - name: Checkout
        uses: actions/checkout@v4       # Clona el repositorio con profundidad 2 para detectar cambios recientes
        with:
          fetch-depth: 2

      - name: Detect changed environments
        id: detect
        run: |
          # Obtiene archivos cambiados entre el último commit y el anterior
          changed_files=$(git diff --name-only HEAD~1 HEAD)
          # Filtra solo los que están dentro de 'environments/', extrae el nombre del entorno y crea una lista JSON
          changed_envs=$(echo "$changed_files" | grep '^environments/' | cut -d'/' -f2 | sort -u | jq -R -s -c 'split("\n")[:-1] | map(select(length > 0))')
          # Pone la lista de entornos modificados en la salida del step
          echo "environments=$changed_envs" >> $GITHUB_OUTPUT
          echo "Changed environments: $changed_envs"  # Muestra en consola para debugging

  terraform:
    name: 'Terraform (${{ matrix.environment }})'
    runs-on: ubuntu-latest              # Runner Ubuntu para ejecutar Terraform
    needs: detect-environments          # Espera a que termine el job de detección
    if: needs.detect-environments.outputs.environments != '[]'  # Solo se ejecuta si detectó entornos modificados
    strategy:
      matrix:
        environment: ${{ fromJson(needs.detect-environments.outputs.environments) }}  # Ejecuta en paralelo para cada entorno detectado

    defaults:
      run:
        shell: bash
        working-directory: ./environments/${{ matrix.environment }}  # Cambia el directorio a la carpeta del entorno

    steps:
      - name: Checkout
        uses: actions/checkout@v4       # Clona el repositorio para este job

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4  # Configura credenciales AWS desde secretos
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}          
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}          
          aws-region: ${{ vars.AWS_REGION }}                           

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3  # Instala la versión 1.5.0 de Terraform CLI
        with:
          terraform_version: "1.5.0"

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive  # Verifica que el código Terraform esté correctamente formateado

      - name: Terraform Init
        id: init
        run: terraform init  # Inicializa Terraform (descarga proveedores y módulos)

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color  # Valida la sintaxis y configuración del código Terraform

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false -var="bucket_name=${{ vars.BUCKET_NAME }}" -var="environment=${{ matrix.environment }}"  
        continue-on-error: true  # No falla el job aunque haya errores para poder revisar el plan

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'  # Si el plan falló, marca el job como fallido
        run: exit 1

  terraform-apply:
    name: 'Terraform Apply (${{ matrix.environment }})'
    runs-on: ubuntu-latest              
    needs: terraform                   
    if: needs.detect-environments.outputs.environments != '[]' && github.ref == 'refs/heads/main' && github.event_name == 'push'
    strategy:
      matrix:
        environment: ${{ fromJson(needs.detect-environments.outputs.environments) }}  # Solo crea la matriz si hay entornos

    defaults:
      run:
        shell: bash
        working-directory: ./environments/${{ matrix.environment }}  

    steps:
      - name: Wait for manual approval
        uses: trstringer/manual-approval@v1   # Acción de aprobación manual para frenar antes del apply
        with:
          approvers: cristopher               # Usuario(s) de GitHub que pueden aprobar
          minimum-approvals: 1                # Cantidad mínima de aprobaciones
          instructions: "Revisá el Terraform Plan generado en el job anterior y aprobá para continuar con el Apply."

      - name: Checkout
        uses: actions/checkout@v4             

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4  
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3    
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init
        run: terraform init                   

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false \
             -var="bucket_name=${{ vars.BUCKET_NAME }}" \
             -var="environment=${{ matrix.environment }}"
